<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'Codigo',
'Nome',
'CPF',
'RG',
'Data de Nascimento',
'Sexo',
'Nome da Mae',
'Nome do Pai',
'E-mail',
'Rua',
'Numero',
'Bairro',
'Cidade',
'Estado',
'Telefone',
'CEP',
'Codagendamento' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'Codigo' => array( 'import_field' ),
'Nome' => array( 'import_field1' ),
'CPF' => array( 'import_field2' ),
'RG' => array( 'import_field3' ),
'Data de Nascimento' => array( 'import_field4' ),
'Sexo' => array( 'import_field5' ),
'Nome da Mae' => array( 'import_field6' ),
'Nome do Pai' => array( 'import_field7' ),
'E-mail' => array( 'import_field8' ),
'Rua' => array( 'import_field9' ),
'Numero' => array( 'import_field10' ),
'Bairro' => array( 'import_field11' ),
'Cidade' => array( 'import_field12' ),
'Estado' => array( 'import_field13' ),
'Telefone' => array( 'import_field14' ),
'CEP' => array( 'import_field15' ),
'Codagendamento' => array( 'import_field16' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'Codigo',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'Nome',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'CPF',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'RG',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'Data de Nascimento',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'Sexo',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'Nome da Mae',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'Nome do Pai',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'E-mail',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'Rua',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'Numero',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'Bairro',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'Cidade',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'Estado',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'Telefone',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'CEP',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'Codagendamento',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>