<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'active' => true,
'code' => '01',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'table' => array( 'connId' => 'ConsultorioOdontologicosqlite3',
'table' => 'Consultorio_Odontologico_usuarios' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => null ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'wyBLO73DymKY0eKoOz07',
'JWTSecret' => 'Z3L2vnrs9OOMAVFR8C1Q' ),
'registration' => array( 'passwordValidation' => array( 'strong' => false,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => false ),
'remindMethod' => 0,
'hashAlgorithm' => 0,
'registerPage' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => '',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'localhost',
'SMTPPort' => 25,
'SMTPUser' => '',
'SMTPPassword' => '',
'securityProtocol' => 0 ),
'advancedSecurity' => array( 'allowGuestLogin' => false,
'tables' => array( 'Atendimento_Agendado' => array( 'mainOwnerIDField' => 'Codigo',
'securityOption' => 1,
'userOwnerIDField' => 'ID' ),
'Consultorio_Odontologico_usuarios' => array( 'mainOwnerIDField' => 'ID',
'securityOption' => 1,
'userOwnerIDField' => 'ID' ),
'Contas_a_pagar' => array( 'mainOwnerIDField' => 'Codigo',
'securityOption' => 1,
'userOwnerIDField' => 'ID' ),
'Contas_pagas' => array( 'mainOwnerIDField' => 'Codigo',
'securityOption' => 1,
'userOwnerIDField' => 'ID' ),
'Dias_Disponiveis' => array( 'mainOwnerIDField' => 'Codigo',
'securityOption' => 1,
'userOwnerIDField' => 'ID' ),
'Fornecedores' => array( 'mainOwnerIDField' => 'Codigo',
'securityOption' => 1,
'userOwnerIDField' => 'ID' ),
'Paciente' => array( 'mainOwnerIDField' => 'Codigo',
'securityOption' => 1,
'userOwnerIDField' => 'ID' ),
'Produtos' => array( 'mainOwnerIDField' => 'Codigo',
'securityOption' => 1,
'userOwnerIDField' => 'ID' ) ) ),
'auditAndLocking' => array( 'loggingTable' => array(  ),
'lockingTable' => array(  ),
'tables' => array(  ),
'loggingMode' => 0,
'loggingFile' => 'audit.log',
'logSecurityActions' => false,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'Consultorio_Odontologico',
'loginDataSource' => 'Consultorio_Odontologico_usuarios',
'loginForm' => 0,
'dynamicPermissions' => false,
'dpTablePrefix' => 'Consultorio_Odontologico',
'dpTableConnId' => 'ConsultorioOdontologicosqlite3',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '01',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'active' => true,
'code' => '01',
'emailField' => 'email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'table' => array( 'connId' => 'ConsultorioOdontologicosqlite3',
'table' => 'Consultorio_Odontologico_usuarios' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => null ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '01' ) );
?>